### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by vdpower** [neherlab/treetime#128]
Hi all,

I would like to know how convert the date foormatfrom a conventional YYYY-MM-DD to YYYY.??, and vice versa, since when i got confidence ranges these are in the numeric date format.

With thanks,
V.

**Comment by josephhughes** [comment]
I have a similar question, I am wondering how the date to decimal.date conversion is done in treetime as the results do not agree with the decimal.date command from lubridate R package.
Thanks

**Comment by rneher** [comment]
your could use these functions in `treetime.utils`:

https://github.com/neherlab/treetime/blob/master/treetime/utils.py#L142

https://github.com/neherlab/treetime/blob/master/treetime/utils.py#L167

These should also show exactly how this conversion is done (basically by looking at the number of days since Jan1st) and then comparing this to 366 or 365 depending on leap year or no.
