### ISSUE TITLE
rescaling treetime clock estimate

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#65]
When I run `treetime clock` on a core alignment, i.e. only variable positions -- how can I rescale the substitution rate estimate? Simply multiply the estimated rate by the rescaling factor as in #63 ?

Thank you.

**Comment by rneher** [comment]
strictly speaking one should recalculate the branch lengths since your ML tree will be calculated under the assumption that every site is variable and hence quite some saturation is happening. if you have your alignment as vcf, `treetime` can use this can recalculate the branch length. I can add a flag to specify the number of constant sites, that would address this. but it'll be a few days. 

for quick and dirty, rescaling the rate estimate should be ok though.

**Comment by phiweger** [comment]
Thank you!

**Comment by rneher** [comment]
hi Adrian,

you could try the following on the branch `constant_sites`:
```
treetime --tree tree.nwk --aln informative_sites.fasta --dates metadata.tsv --sequence-length 4500000
```
this should calculate a time tree including the rate estimation etc on an alignment of informative sites only. It will determine the mix of ACGT from those informative sites and than add additional columns such that the total sequence length is as specified. it should output a timetree, a mutation tree, and the root-to-tip regression.

**Comment by rneher** [comment]
@phiweger, did this work for you?

**Comment by phiweger** [comment]
Sorry for the late reply, yes, it worked -- thank you for putting this feature in the code so quickly!
